### ISSUE TITLE
Accept this answer shown on initial post?

### ISSUE THREAD

**Issue by tripflex** [tierra/topicsolved#51]
Not sure if that's by design or not, but it would be nice to be able to disable having it show the "Accept this answer" on the initial post, as if you're using this for support forum ... chances are the first post is going to be the user asking for help, which would IMO never end up being an accepted answer.

**Comment by tripflex** [comment]
For anybody that wants this same functionality, I just used CSS3 to hide the first one:

``` css
.content-main-inner > div:nth-of-type(1) .topicsolved-icon {
    display: none;
}
```
